# Project Makefile #

PROJECT_NAME := mpu-i2c

# Path to MPU Driver
EXTRA_COMPONENT_DIRS += $(abspath ../..)
# Path to I2Cbus
EXTRA_COMPONENT_DIRS += ${HOME}/esp/libraries/I2Cbus


include $(IDF_PATH)/make/project.mk
