# Project Makefile #

PROJECT_NAME := mpu-spi

# Path to MPU Driver
EXTRA_COMPONENT_DIRS += $(abspath ../..)
# Path to SPIbus
EXTRA_COMPONENT_DIRS += ${HOME}/esp/libraries/SPIbus


include $(IDF_PATH)/make/project.mk
