#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := mpu-inv
EXTRA_COMPONENT_DIRS := ${HOME}/esp/libraries

include $(IDF_PATH)/make/project.mk
