#
# This is a project Makefile.
#

PROJECT_NAME := raw-data-graph

# Add here path to I2Cbus library
EXTRA_COMPONENT_DIRS := ${HOME}/esp/libraries/I2Cbus

# Path to the MPU library
EXTRA_COMPONENT_DIRS += $(abspath ../..)

include $(IDF_PATH)/make/project.mk
