# Project Makefile #

PROJECT_NAME := mpu-real

# Path to MPU Driver
EXTRA_COMPONENT_DIRS += $(abspath ../..)
# Path to I2Cbus
EXTRA_COMPONENT_DIRS += ${HOME}/esp/libraries/I2Cbus
# Path to SPIbus
EXTRA_COMPONENT_DIRS += ${HOME}/esp/libraries/SPIbus


include $(IDF_PATH)/make/project.mk
